services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: grupo5-api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
